// ⚠️ DO NOT CHANGE OR REMOVE THIS FILE, IT IS AUTO GENERATED BY THE BETTERDEBUG EXTENSION
const extensionPath = 'c:/CodeProjects_Insync/_MadeInCursor/log-all-lines-mcp/betterdebug'
module.exports = require(extensionPath + '/out/frameworks/nextjs.js').default({ extensionPath })
// ⚠️ DO NOT CHANGE OR REMOVE THIS FILE, IT IS AUTO GENERATED BY THE BETTERDEBUG EXTENSION
